// Generated data using https://www.w3schools.com/icons/icons_reference.asp, MS Excel and notepad++ macros.
MGFonts = {
    getFontAwesomeIcons: function () {
        return ['fa fa-500px',
                    'fa fa-address-book',
                    'fa fa-address-book-o',
                    'fa fa-address-card',
                    'fa fa-address-card-o',
                    'fa fa-adjust',
                    'fa fa-adn',
                    'fa fa-align-center',
                    'fa fa-align-justify',
                    'fa fa-align-left',
                    'fa fa-align-right',
                    'fa fa-amazon',
                    'fa fa-ambulance',
                    'fa fa-american-sign-language-interpreting',
                    'fa fa-anchor',
                    'fa fa-android',
                    'fa fa-angellist',
                    'fa fa-angle-double-down',
                    'fa fa-angle-double-left',
                    'fa fa-angle-double-right',
                    'fa fa-angle-double-up',
                    'fa fa-angle-down',
                    'fa fa-angle-left',
                    'fa fa-angle-right',
                    'fa fa-angle-up',
                    'fa fa-apple',
                    'fa fa-archive',
                    'fa fa-area-chart',
                    'fa fa-arrow-circle-down',
                    'fa fa-arrow-circle-left',
                    'fa fa-arrow-circle-o-down',
                    'fa fa-arrow-circle-o-left',
                    'fa fa-arrow-circle-o-right',
                    'fa fa-arrow-circle-o-up',
                    'fa fa-arrow-circle-right',
                    'fa fa-arrow-circle-up',
                    'fa fa-arrow-down',
                    'fa fa-arrow-left',
                    'fa fa-arrow-right',
                    'fa fa-arrow-up',
                    'fa fa-arrows',
                    'fa fa-arrows-alt',
                    'fa fa-arrows-h',
                    'fa fa-arrows-v',
                    'fa fa-asl-interpreting',
                    'fa fa-assistive-listening-systems',
                    'fa fa-asterisk',
                    'fa fa-at',
                    'fa fa-audio-description',
                    'fa fa-automobile',
                    'fa fa-backward',
                    'fa fa-balance-scale',
                    'fa fa-ban',
                    'fa fa-bandcamp',
                    'fa fa-bank',
                    'fa fa-bar-chart',
                    'fa fa-bar-chart-o',
                    'fa fa-barcode',
                    'fa fa-bars',
                    'fa fa-bath',
                    'fa fa-bathtub',
                    'fa fa-battery-empty',
                    'fa fa-battery-full',
                    'fa fa-battery-half',
                    'fa fa-battery-quarter',
                    'fa fa-battery-three-quarters',
                    'fa fa-bed',
                    'fa fa-beer',
                    'fa fa-behance',
                    'fa fa-behance-square',
                    'fa fa-bell',
                    'fa fa-bell-o',
                    'fa fa-bell-slash',
                    'fa fa-bell-slash-o',
                    'fa fa-bicycle',
                    'fa fa-binoculars',
                    'fa fa-birthday-cake',
                    'fa fa-bitbucket',
                    'fa fa-bitbucket-square',
                    'fa fa-bitcoin',
                    'fa fa-black-tie',
                    'fa fa-blind',
                    'fa fa-bluetooth',
                    'fa fa-bluetooth-b',
                    'fa fa-bold',
                    'fa fa-bolt',
                    'fa fa-bomb',
                    'fa fa-book',
                    'fa fa-bookmark',
                    'fa fa-bookmark-o',
                    'fa fa-braille',
                    'fa fa-briefcase',
                    'fa fa-btc',
                    'fa fa-bug',
                    'fa fa-building',
                    'fa fa-building-o',
                    'fa fa-bullhorn',
                    'fa fa-bullseye',
                    'fa fa-bus',
                    'fa fa-buysellads',
                    'fa fa-cab',
                    'fa fa-calculator',
                    'fa fa-calendar',
                    'fa fa-calendar-check-o',
                    'fa fa-calendar-minus-o',
                    'fa fa-calendar-o',
                    'fa fa-calendar-plus-o',
                    'fa fa-calendar-times-o',
                    'fa fa-camera',
                    'fa fa-camera-retro',
                    'fa fa-car',
                    'fa fa-caret-down',
                    'fa fa-caret-left',
                    'fa fa-caret-right',
                    'fa fa-caret-square-o-down',
                    'fa fa-caret-square-o-left',
                    'fa fa-caret-square-o-right',
                    'fa fa-caret-square-o-up',
                    'fa fa-caret-up',
                    'fa fa-cart-arrow-down',
                    'fa fa-cart-plus',
                    'fa fa-cc',
                    'fa fa-cc-amex',
                    'fa fa-cc-diners-club',
                    'fa fa-cc-discover',
                    'fa fa-cc-jcb',
                    'fa fa-cc-mastercard',
                    'fa fa-cc-paypal',
                    'fa fa-cc-stripe',
                    'fa fa-cc-visa',
                    'fa fa-certificate',
                    'fa fa-chain',
                    'fa fa-chain-broken',
                    'fa fa-check',
                    'fa fa-check-circle',
                    'fa fa-check-circle-o',
                    'fa fa-check-square',
                    'fa fa-check-square-o',
                    'fa fa-chevron-circle-down',
                    'fa fa-chevron-circle-left',
                    'fa fa-chevron-circle-right',
                    'fa fa-chevron-circle-up',
                    'fa fa-chevron-down',
                    'fa fa-chevron-left',
                    'fa fa-chevron-right',
                    'fa fa-chevron-up',
                    'fa fa-child',
                    'fa fa-chrome',
                    'fa fa-circle',
                    'fa fa-circle-o',
                    'fa fa-circle-o-notch',
                    'fa fa-circle-thin',
                    'fa fa-clipboard',
                    'fa fa-clock-o',
                    'fa fa-clone',
                    'fa fa-close',
                    'fa fa-cloud',
                    'fa fa-cloud-download',
                    'fa fa-cloud-upload',
                    'fa fa-cny',
                    'fa fa-code',
                    'fa fa-code-fork',
                    'fa fa-codepen',
                    'fa fa-codiepie',
                    'fa fa-coffee',
                    'fa fa-cog',
                    'fa fa-cogs',
                    'fa fa-columns',
                    'fa fa-comment',
                    'fa fa-comment-o',
                    'fa fa-comments',
                    'fa fa-comments-o',
                    'fa fa-commenting',
                    'fa fa-commenting-o',
                    'fa fa-compass',
                    'fa fa-compress',
                    'fa fa-connectdevelop',
                    'fa fa-contao',
                    'fa fa-copy',
                    'fa fa-copyright',
                    'fa fa-creative-commons',
                    'fa fa-credit-card',
                    'fa fa-credit-card-alt',
                    'fa fa-crop',
                    'fa fa-crosshairs',
                    'fa fa-css3',
                    'fa fa-cube',
                    'fa fa-cubes',
                    'fa fa-cut',
                    'fa fa-cutlery',
                    'fa fa-dashboard',
                    'fa fa-dashcube',
                    'fa fa-database',
                    'fa fa-deaf',
                    'fa fa-deafness',
                    'fa fa-dedent',
                    'fa fa-delicious',
                    'fa fa-desktop',
                    'fa fa-deviantart',
                    'fa fa-diamond',
                    'fa fa-digg',
                    'fa fa-dollar',
                    'fa fa-dot-circle-o',
                    'fa fa-download',
                    'fa fa-dribbble',
                    'fa fa-drivers-license',
                    'fa fa-drivers-license-o',
                    'fa fa-dropbox',
                    'fa fa-drupal',
                    'fa fa-edge',
                    'fa fa-edit',
                    'fa fa-eercast',
                    'fa fa-eject',
                    'fa fa-ellipsis-h',
                    'fa fa-ellipsis-v',
                    'fa fa-empire',
                    'fa fa-envelope',
                    'fa fa-envelope-o',
                    'fa fa-envelope-open',
                    'fa fa-envelope-open-o',
                    'fa fa-envelope-square',
                    'fa fa-envira',
                    'fa fa-eraser',
                    'fa fa-etsy',
                    'fa fa-eur',
                    'fa fa-euro',
                    'fa fa-exchange',
                    'fa fa-exclamation',
                    'fa fa-exclamation-circle',
                    'fa fa-exclamation-triangle',
                    'fa fa-expand',
                    'fa fa-expeditedssl',
                    'fa fa-external-link',
                    'fa fa-external-link-square',
                    'fa fa-eye',
                    'fa fa-eye-slash',
                    'fa fa-eyedropper',
                    'fa fa-font-awesome',
                    'fa fa-facebook',
                    'fa fa-facebook-f',
                    'fa fa-facebook-official',
                    'fa fa-facebook-square',
                    'fa fa-fast-backward',
                    'fa fa-fast-forward',
                    'fa fa-fax',
                    'fa fa-feed',
                    'fa fa-female',
                    'fa fa-fighter-jet',
                    'fa fa-file',
                    'fa fa-file-archive-o',
                    'fa fa-file-audio-o',
                    'fa fa-file-code-o',
                    'fa fa-file-excel-o',
                    'fa fa-file-image-o',
                    'fa fa-file-movie-o',
                    'fa fa-file-o',
                    'fa fa-file-pdf-o',
                    'fa fa-file-photo-o',
                    'fa fa-file-picture-o',
                    'fa fa-file-powerpoint-o',
                    'fa fa-file-sound-o',
                    'fa fa-file-text',
                    'fa fa-file-text-o',
                    'fa fa-file-video-o',
                    'fa fa-file-word-o',
                    'fa fa-file-zip-o',
                    'fa fa-files-o',
                    'fa fa-film',
                    'fa fa-filter',
                    'fa fa-fire',
                    'fa fa-fire-extinguisher',
                    'fa fa-firefox',
                    'fa fa-first-order',
                    'fa fa-flag',
                    'fa fa-flag-checkered',
                    'fa fa-flag-o',
                    'fa fa-flash',
                    'fa fa-flask',
                    'fa fa-flickr',
                    'fa fa-floppy-o',
                    'fa fa-folder',
                    'fa fa-folder-o',
                    'fa fa-folder-open',
                    'fa fa-folder-open-o',
                    'fa fa-font',
                    'fa fa-font-awesome',
                    'fa fa-fonticons',
                    'fa fa-fort-awesome',
                    'fa fa-forumbee',
                    'fa fa-forward',
                    'fa fa-foursquare',
                    'fa fa-free-code-camp',
                    'fa fa-frown-o',
                    'fa fa-futbol-o',
                    'fa fa-gamepad',
                    'fa fa-gavel',
                    'fa fa-gbp',
                    'fa fa-ge',
                    'fa fa-gear',
                    'fa fa-gears',
                    'fa fa-genderless',
                    'fa fa-get-pocket',
                    'fa fa-gg',
                    'fa fa-gg-circle',
                    'fa fa-gift',
                    'fa fa-git',
                    'fa fa-git-square',
                    'fa fa-github',
                    'fa fa-github-alt',
                    'fa fa-github-square',
                    'fa fa-gitlab',
                    'fa fa-gittip',
                    'fa fa-glass',
                    'fa fa-glide',
                    'fa fa-glide-g',
                    'fa fa-globe',
                    'fa fa-google',
                    'fa fa-google-plus',
                    'fa fa-google-plus-circle',
                    'fa fa-google-plus-official',
                    'fa fa-google-plus-square',
                    'fa fa-google-wallet',
                    'fa fa-graduation-cap',
                    'fa fa-gratipay',
                    'fa fa-grav',
                    'fa fa-group',
                    'fa fa-h-square',
                    'fa fa-hacker-news',
                    'fa fa-hand-grab-o',
                    'fa fa-hand-lizard-o',
                    'fa fa-hand-o-down',
                    'fa fa-hand-o-left',
                    'fa fa-hand-o-right',
                    'fa fa-hand-o-up',
                    'fa fa-hand-paper-o',
                    'fa fa-hand-peace-o',
                    'fa fa-hand-pointer-o',
                    'fa fa-hand-rock-o',
                    'fa fa-hand-scissors-o',
                    'fa fa-hand-spock-o',
                    'fa fa-hand-stop-o',
                    'fa fa-handshake-o',
                    'fa fa-hard-of-hearing',
                    'fa fa-hashtag',
                    'fa fa-hdd-o',
                    'fa fa-header',
                    'fa fa-headphones',
                    'fa fa-heart',
                    'fa fa-heart-o',
                    'fa fa-heartbeat',
                    'fa fa-history',
                    'fa fa-home',
                    'fa fa-hospital-o',
                    'fa fa-hotel',
                    'fa fa-hourglass',
                    'fa fa-hourglass-end',
                    'fa fa-hourglass-half',
                    'fa fa-hourglass-o',
                    'fa fa-hourglass-start',
                    'fa fa-houzz',
                    'fa fa-html5',
                    'fa fa-i-cursor',
                    'fa fa-id-badge',
                    'fa fa-id-card',
                    'fa fa-id-card-o',
                    'fa fa-ils',
                    'fa fa-image',
                    'fa fa-imdb',
                    'fa fa-inbox',
                    'fa fa-indent',
                    'fa fa-industry',
                    'fa fa-info',
                    'fa fa-info-circle',
                    'fa fa-inr',
                    'fa fa-instagram',
                    'fa fa-institution',
                    'fa fa-internet-explorer',
                    'fa fa-intersex',
                    'fa fa-ioxhost',
                    'fa fa-italic',
                    'fa fa-joomla',
                    'fa fa-jpy',
                    'fa fa-jsfiddle',
                    'fa fa-key',
                    'fa fa-keyboard-o',
                    'fa fa-krw',
                    'fa fa-language',
                    'fa fa-laptop',
                    'fa fa-lastfm',
                    'fa fa-lastfm-square',
                    'fa fa-leaf',
                    'fa fa-leanpub',
                    'fa fa-legal',
                    'fa fa-lemon-o',
                    'fa fa-level-down',
                    'fa fa-level-up',
                    'fa fa-life-bouy',
                    'fa fa-life-buoy',
                    'fa fa-life-ring',
                    'fa fa-life-saver',
                    'fa fa-lightbulb-o',
                    'fa fa-line-chart',
                    'fa fa-link',
                    'fa fa-linkedin',
                    'fa fa-linkedin-square',
                    'fa fa-linode8',
                    'fa fa-linux',
                    'fa fa-list',
                    'fa fa-list-alt',
                    'fa fa-list-ul',
                    'fa fa-location-arrow',
                    'fa fa-lock',
                    'fa fa-long-arrow-down',
                    'fa fa-long-arrow-left',
                    'fa fa-long-arrow-right',
                    'fa fa-long-arrow-up',
                    'fa fa-low-vision',
                    'fa fa-magic',
                    'fa fa-magnet',
                    'fa fa-mail-forward',
                    'fa fa-mail-reply',
                    'fa fa-mail-reply-all',
                    'fa fa-male',
                    'fa fa-map',
                    'fa fa-map-marker',
                    'fa fa-map-o',
                    'fa fa-map-pin',
                    'fa fa-map-signs',
                    'fa fa-mars',
                    'fa fa-mars-double',
                    'fa fa-mars-stroke',
                    'fa fa-mars-stroke-h',
                    'fa fa-mars-stroke-v',
                    'fa fa-maxcdn',
                    'fa fa-meanpath',
                    'fa fa-medium',
                    'fa fa-medkit',
                    'fa fa-meetup',
                    'fa fa-meh-o',
                    'fa fa-mercury',
                    'fa fa-microchip',
                    'fa fa-microphone',
                    'fa fa-microphone-slash',
                    'fa fa-minus',
                    'fa fa-minus-circle',
                    'fa fa-minus-square',
                    'fa fa-minus-square-o',
                    'fa fa-mixcloud',
                    'fa fa-mobile',
                    'fa fa-mobile-phone',
                    'fa fa-modx',
                    'fa fa-money',
                    'fa fa-moon-o',
                    'fa fa-mortar-board',
                    'fa fa-motorcycle',
                    'fa fa-mouse-pointer',
                    'fa fa-music',
                    'fa fa-navicon',
                    'fa fa-neuter',
                    'fa fa-newspaper-o',
                    'fa fa-object-group',
                    'fa fa-object-ungroup',
                    'fa fa-odnoklassniki',
                    'fa fa-odnoklassniki-square',
                    'fa fa-opencart',
                    'fa fa-openid',
                    'fa fa-opera',
                    'fa fa-optin-monster',
                    'fa fa-outdent',
                    'fa fa-paint-brush',
                    'fa fa-pagelines',
                    'fa fa-paper-plane',
                    'fa fa-paper-plane-o',
                    'fa fa-paperclip',
                    'fa fa-paragraph',
                    'fa fa-paste',
                    'fa fa-pause',
                    'fa fa-pause-circle',
                    'fa fa-pause-circle-o',
                    'fa fa-paw',
                    'fa fa-paypal',
                    'fa fa-pencil',
                    'fa fa-pencil-square',
                    'fa fa-pencil-square-o',
                    'fa fa-percent',
                    'fa fa-phone',
                    'fa fa-phone-square',
                    'fa fa-photo',
                    'fa fa-picture-o',
                    'fa fa-pie-chart',
                    'fa fa-pied-piper',
                    'fa fa-pied-piper-alt',
                    'fa fa-pied-piper-pp',
                    'fa fa-pinterest',
                    'fa fa-pinterest-p',
                    'fa fa-pinterest-square',
                    'fa fa-plane',
                    'fa fa-play',
                    'fa fa-play-circle',
                    'fa fa-play-circle-o',
                    'fa fa-plug',
                    'fa fa-plus',
                    'fa fa-plus-circle',
                    'fa fa-plus-square',
                    'fa fa-plus-square-o',
                    'fa fa-podcast',
                    'fa fa-power-off',
                    'fa fa-print',
                    'fa fa-product-hunt',
                    'fa fa-puzzle-piece',
                    'fa fa-qq',
                    'fa fa-qrcode',
                    'fa fa-question',
                    'fa fa-question-circle',
                    'fa fa-question-circle-o',
                    'fa fa-quora',
                    'fa fa-quote-left',
                    'fa fa-quote-right',
                    'fa fa-ra',
                    'fa fa-random',
                    'fa fa-ravelry',
                    'fa fa-rebel',
                    'fa fa-recycle',
                    'fa fa-reddit',
                    'fa fa-reddit-alien',
                    'fa fa-reddit-square',
                    'fa fa-refresh',
                    'fa fa-registered',
                    'fa fa-remove',
                    'fa fa-renren',
                    'fa fa-reorder',
                    'fa fa-repeat',
                    'fa fa-reply',
                    'fa fa-reply-all',
                    'fa fa-resistance',
                    'fa fa-retweet',
                    'fa fa-rmb',
                    'fa fa-road',
                    'fa fa-rocket',
                    'fa fa-rotate-left',
                    'fa fa-rotate-right',
                    'fa fa-rouble',
                    'fa fa-rss',
                    'fa fa-rss-square',
                    'fa fa-rub',
                    'fa fa-ruble',
                    'fa fa-rupee',
                    'fa fa-s15',
                    'fa fa-safari',
                    'fa fa-save',
                    'fa fa-scissors',
                    'fa fa-scribd',
                    'fa fa-search',
                    'fa fa-search-minus',
                    'fa fa-search-plus',
                    'fa fa-sellsy',
                    'fa fa-send',
                    'fa fa-send-o',
                    'fa fa-server',
                    'fa fa-share',
                    'fa fa-share-alt',
                    'fa fa-share-alt-square',
                    'fa fa-share-square',
                    'fa fa-share-square-o',
                    'fa fa-shekel',
                    'fa fa-sheqel',
                    'fa fa-shield',
                    'fa fa-ship',
                    'fa fa-shirtsinbulk',
                    'fa fa-shopping-bag',
                    'fa fa-shopping-basket',
                    'fa fa-shopping-cart',
                    'fa fa-shower',
                    'fa fa-sign-in',
                    'fa fa-sign-language',
                    'fa fa-sign-out',
                    'fa fa-signal',
                    'fa fa-signing',
                    'fa fa-simplybuilt',
                    'fa fa-sitemap',
                    'fa fa-skyatlas',
                    'fa fa-skype',
                    'fa fa-slack',
                    'fa fa-sliders',
                    'fa fa-slideshare',
                    'fa fa-smile-o',
                    'fa fa-snapchat',
                    'fa fa-snapchat-ghost',
                    'fa fa-snapchat-square',
                    'fa fa-snowflake-o',
                    'fa fa-soccer-ball-o',
                    'fa fa-sort',
                    'fa fa-sort-alpha-asc',
                    'fa fa-sort-alpha-desc',
                    'fa fa-sort-amount-asc',
                    'fa fa-sort-amount-desc',
                    'fa fa-sort-asc',
                    'fa fa-sort-desc',
                    'fa fa-sort-down',
                    'fa fa-sort-numeric-asc',
                    'fa fa-sort-numeric-desc',
                    'fa fa-sort-up',
                    'fa fa-soundcloud',
                    'fa fa-space-shuttle',
                    'fa fa-spinner',
                    'fa fa-spoon',
                    'fa fa-spotify',
                    'fa fa-square',
                    'fa fa-square-o',
                    'fa fa-stack-exchange',
                    'fa fa-stack-overflow',
                    'fa fa-star',
                    'fa fa-star-half',
                    'fa fa-star-half-empty',
                    'fa fa-star-half-full',
                    'fa fa-star-half-o',
                    'fa fa-star-o',
                    'fa fa-steam',
                    'fa fa-steam-square',
                    'fa fa-step-backward',
                    'fa fa-step-forward',
                    'fa fa-stethoscope',
                    'fa fa-sticky-note',
                    'fa fa-sticky-note-o',
                    'fa fa-stop',
                    'fa fa-stop-circle',
                    'fa fa-stop-circle-o',
                    'fa fa-street-view',
                    'fa fa-strikethrough',
                    'fa fa-stumbleupon',
                    'fa fa-stumbleupon-circle',
                    'fa fa-subscript',
                    'fa fa-subway',
                    'fa fa-suitcase',
                    'fa fa-sun-o',
                    'fa fa-superpowers',
                    'fa fa-superscript',
                    'fa fa-support',
                    'fa fa-table',
                    'fa fa-tablet',
                    'fa fa-tachometer',
                    'fa fa-tag',
                    'fa fa-tags',
                    'fa fa-tasks',
                    'fa fa-taxi',
                    'fa fa-telegram',
                    'fa fa-television',
                    'fa fa-tencent-weibo',
                    'fa fa-terminal',
                    'fa fa-text-height',
                    'fa fa-text-width',
                    'fa fa-th',
                    'fa fa-th-large',
                    'fa fa-th-list',
                    'fa fa-themeisle',
                    'fa fa-thermometer-3',
                    'fa fa-thermometer-empty',
                    'fa fa-thermometer-full',
                    'fa fa-thermometer-half',
                    'fa fa-thermometer-quarter',
                    'fa fa-thermometer-three-quarters',
                    'fa fa-thumb-tack',
                    'fa fa-thumbs-down',
                    'fa fa-thumbs-o-down',
                    'fa fa-thumbs-o-up',
                    'fa fa-thumbs-up',
                    'fa fa-ticket',
                    'fa fa-times',
                    'fa fa-times-circle',
                    'fa fa-times-circle-o',
                    'fa fa-times-rectangle',
                    'fa fa-times-rectangle-o',
                    'fa fa-tint',
                    'fa fa-toggle-down',
                    'fa fa-toggle-left',
                    'fa fa-toggle-off',
                    'fa fa-toggle-on',
                    'fa fa-toggle-right',
                    'fa fa-toggle-up',
                    'fa fa-trademark',
                    'fa fa-train',
                    'fa fa-transgender',
                    'fa fa-transgender-alt',
                    'fa fa-trash',
                    'fa fa-trash-o',
                    'fa fa-tree',
                    'fa fa-trello',
                    'fa fa-tripadvisor',
                    'fa fa-trophy',
                    'fa fa-truck',
                    'fa fa-try',
                    'fa fa-tty',
                    'fa fa-tumblr',
                    'fa fa-tumblr-square',
                    'fa fa-turkish-lira',
                    'fa fa-tv',
                    'fa fa-twitch',
                    'fa fa-twitter',
                    'fa fa-twitter-square',
                    'fa fa-umbrella',
                    'fa fa-underline',
                    'fa fa-undo',
                    'fa fa-universal-access',
                    'fa fa-university',
                    'fa fa-unlink',
                    'fa fa-unlock',
                    'fa fa-unlock-alt',
                    'fa fa-unsorted',
                    'fa fa-upload',
                    'fa fa-usb',
                    'fa fa-usd',
                    'fa fa-user',
                    'fa fa-user-circle',
                    'fa fa-user-circle-o',
                    'fa fa-user-md',
                    'fa fa-user-o',
                    'fa fa-user-plus',
                    'fa fa-user-secret',
                    'fa fa-user-times',
                    'fa fa-users',
                    'fa fa-vcard',
                    'fa fa-vcard-o',
                    'fa fa-venus',
                    'fa fa-venus-double',
                    'fa fa-venus-mars',
                    'fa fa-viacoin',
                    'fa fa-viadeo',
                    'fa fa-viadeo-square',
                    'fa fa-video-camera',
                    'fa fa-vimeo',
                    'fa fa-vimeo-square',
                    'fa fa-vine',
                    'fa fa-vk',
                    'fa fa-volume-control-phone',
                    'fa fa-volume-down',
                    'fa fa-volume-off',
                    'fa fa-volume-up',
                    'fa fa-warning',
                    'fa fa-wechat',
                    'fa fa-weibo',
                    'fa fa-weixin',
                    'fa fa-whatsapp',
                    'fa fa-wheelchair',
                    'fa fa-wheelchair-alt',
                    'fa fa-wifi',
                    'fa fa-wikipedia-w',
                    'fa fa-window-close',
                    'fa fa-window-close-o',
                    'fa fa-window-maximize',
                    'fa fa-window-minimize',
                    'fa fa-window-restore',
                    'fa fa-windows',
                    'fa fa-won',
                    'fa fa-wordpress',
                    'fa fa-wpbeginner',
                    'fa fa-wpexplorer',
                    'fa fa-wpforms',
                    'fa fa-wrench',
                    'fa fa-xing',
                    'fa fa-xing-square',
                    'fa fa-y-combinator',
                    'fa fa-y-combinator-square',
                    'fa fa-yahoo',
                    'fa fa-yc',
                    'fa fa-yc-square',
                    'fa fa-yelp',
                    'fa fa-yen',
                    'fa fa-yoast',
                    'fa fa-youtube',
                    'fa fa-youtube-play',
                    'fa fa-youtube-square'];
    },

    getGoogleFontIcons: function () {
        return ['3d_rotation',
                'ac_unit',
                'access_alarm',
                'access_alarms',
                'access_time',
                'accessibility',
                'accessible',
                'account_balance',
                'account_balance_wallet',
                'account_box',
                'account_circle',
                'adb',
                'add',
                'add_a_photo',
                'add_alarm',
                'add_alert',
                'add_box',
                'add_circle',
                'add_circle_outline',
                'add_shopping_cart',
                'add_to_photos',
                'add_to_queue',
                'adjust',
                'airline_seat_flat',
                'airline_seat_flat_angled',
                'airline_seat_individual_suite',
                'airline_seat_legroom_extra',
                'airline_seat_legroom_normal',
                'airline_seat_legroom_reduced',
                'airline_seat_recline_extra',
                'airline_seat_recline_normal',
                'airplanemode_active',
                'airplanemode_inactive',
                'airplay',
                'airport_shuttle',
                'alarm',
                'alarm_add',
                'alarm_off',
                'alarm_on',
                'album',
                'all_out',
                'all_inclusive',
                'android',
                'announcement',
                'apps',
                'archive',
                'arrow_back',
                'arrow_drop_down',
                'arrow_drop_down_circle',
                'arrow_drop_up',
                'arrow_downward',
                'arrow_forward',
                'arrow_upward',
                'art_track',
                'aspect_ratio',
                'assessment',
                'assignment',
                'assignment_ind',
                'assignment_late',
                'assignment_return',
                'assignment_returned',
                'assignment_turned_in',
                'assistant',
                'assistant_photo',
                'attach_file',
                'attach_money',
                'attachment',
                'audiotrack',
                'autorenew',
                'av_timer',
                'backspace',
                'backup',
                'battery_alert',
                'battery_charging_full',
                'battery_full',
                'battery_std',
                'battery_unknown',
                'beach_access',
                'beenhere',
                'block',
                'bluetooth',
                'bluetooth_audio',
                'bluetooth_connected',
                'bluetooth_disabled',
                'bluetooth_searching',
                'blur_circular',
                'blur_linear',
                'blur_off',
                'blur_on',
                'book',
                'bookmark',
                'bookmark_border',
                'border_all',
                'border_bottom',
                'border_clear',
                'border_color',
                'border_horizontal',
                'border_inner',
                'border_left',
                'border_outer',
                'border_right',
                'border_style',
                'border_top',
                'border_vertical',
                'branding_watermark',
                'brightness_auto',
                'brightness_high',
                'brightness_low',
                'brightness_medium',
                'broken_image',
                'brush',
                'bubble_chart',
                'bug_report',
                'build',
                'burst_mode',
                'business',
                'business_center',
                'cake',
                'call_to_action',
                'cached',
                'call',
                'call_end',
                'call_made',
                'call_merge',
                'call_missed',
                'call_missed_outgoing',
                'call_received',
                'call_split',
                'camera',
                'camera_alt',
                'camera_enhance',
                'camera_front',
                'camera_rear',
                'camera_roll',
                'cancel',
                'card_giftcard',
                'card_membership',
                'card_travel',
                'casino',
                'cast',
                'cast_connected',
                'center_focus_strong',
                'center_focus_weak',
                'change_history',
                'chat',
                'chat_bubble',
                'chat_bubble_outline',
                'check',
                'check_box',
                'check_box_outline_blank',
                'check_circle',
                'chevron_left',
                'chevron_right',
                'child_care',
                'child_friendly',
                'chrome_reader_mode',
                'class',
                'clear',
                'clear_all',
                'close',
                'closed_caption',
                'cloud',
                'cloud_circle',
                'cloud_done',
                'cloud_download',
                'cloud_off',
                'cloud_queue',
                'cloud_upload',
                'code',
                'collections',
                'collections_bookmark',
                'color_lens',
                'colorize',
                'comment',
                'compare',
                'compare_arrows',
                'computer',
                'confirmation_number',
                'contact_phone',
                'contact_mail',
                'contacts',
                'content_copy',
                'content_cut',
                'content_paste',
                'control_point',
                'control_point_duplicate',
                'copyright',
                'create',
                'create_new_folder',
                'credit_card',
                'crop',
                'crop_din',
                'crop_free',
                'crop_landscape',
                'crop_original',
                'crop_portrait',
                'crop_square',
                'dashboard',
                'date_range',
                'data_usage',
                'dehaze',
                'delete',
                'delete_forever',
                'delete_sweep',
                'description',
                'desktop_mac',
                'desktop_windows',
                'developer_board',
                'developer_mode',
                'details',
                'device_hub',
                'devices_other',
                'devices',
                'dialer_sip',
                'dialpad',
                'directions',
                'directions_bike',
                'directions_boat',
                'directions_bus',
                'directions_car',
                'directions_railway',
                'directions_run',
                'directions_subway',
                'directions_transit',
                'directions_walk',
                'disc_full',
                'dns',
                'do_not_disturb',
                'do_not_disturb_alt',
                'do_not_disturb_off',
                'do_not_disturb_on',
                'dock',
                'domain',
                'done',
                'done_all',
                'donut_large',
                'donut_small',
                'drafts',
                'drag_handle',
                'drive_eta',
                'dvr',
                'edit',
                'edit_location',
                'eject',
                'email',
                'enhanced_encryption',
                'equalizer',
                'error',
                'error_outline',
                'euro_symbol',
                'ev_station',
                'event',
                'event_available',
                'event_busy',
                'event_note',
                'event_seat',
                'exit_to_app',
                'expand_less',
                'expand_more',
                'explicit',
                'explore',
                'exposure',
                'exposure_zero',
                'extension',
                'face',
                'fast_forward',
                'fast_rewind',
                'favorite',
                'favorite_border',
                'featured_play_list',
                'featured_video',
                'feedback',
                'fiber_dvr',
                'fiber_manual_record',
                'fiber_new',
                'fiber_pin',
                'fiber_smart_record',
                'file_download',
                'file_upload',
                'filter',
                'filter_center_focus',
                'filter_drama',
                'filter_frames',
                'filter_hdr',
                'filter_list',
                'filter_none',
                'filter_tilt_shift',
                'filter_vintage',
                'find_in_page',
                'find_replace',
                'fingerprint',
                'first_page',
                'fitness_center',
                'flag',
                'flare',
                'flash_auto',
                'flash_off',
                'flash_on',
                'flight',
                'flight_land',
                'flight_takeoff',
                'flip',
                'flip_to_back',
                'flip_to_front',
                'folder',
                'folder_open',
                'folder_shared',
                'folder_special',
                'font_download',
                'format_align_center',
                'format_align_justify',
                'format_align_left',
                'format_align_right',
                'format_bold',
                'format_clear',
                'format_color_fill',
                'format_color_reset',
                'format_color_text',
                'format_indent_decrease',
                'format_indent_increase',
                'format_italic',
                'format_line_spacing',
                'format_list_bulleted',
                'format_list_numbered',
                'format_paint',
                'format_quote',
                'format_shapes',
                'format_size',
                'format_strikethrough',
                'format_textdirection_l_to_r',
                'format_textdirection_r_to_l',
                'format_underlined',
                'forum',
                'forward',
                'free_breakfast',
                'fullscreen',
                'fullscreen_exit',
                'functions',
                'g_translate',
                'gamepad',
                'games',
                'gavel',
                'gesture',
                'get_app',
                'gif',
                'golf_course',
                'gps_fixed',
                'gps_not_fixed',
                'gps_off',
                'grade',
                'gradient',
                'grain',
                'graphic_eq',
                'grid_off',
                'grid_on',
                'group',
                'group_add',
                'group_work',
                'hd',
                'hdr_off',
                'hdr_on',
                'hdr_strong',
                'hdr_weak',
                'headset',
                'headset_mic',
                'healing',
                'hearing',
                'help',
                'help_outline',
                'high_quality',
                'highlight',
                'highlight_off',
                'history',
                'home',
                'hot_tub',
                'hotel',
                'hourglass_empty',
                'hourglass_full',
                'http',
                'https',
                'image',
                'image_aspect_ratio',
                'import_contacts',
                'import_export',
                'important_devices',
                'inbox',
                'indeterminate_check_box',
                'info',
                'info_outline',
                'input',
                'insert_chart',
                'insert_comment',
                'insert_drive_file',
                'insert_emoticon',
                'insert_invitation',
                'insert_link',
                'insert_photo',
                'invert_colors',
                'invert_colors_off',
                'iso',
                'keyboard',
                'keyboard_arrow_down',
                'keyboard_arrow_left',
                'keyboard_arrow_right',
                'keyboard_arrow_up',
                'keyboard_backspace',
                'keyboard_capslock',
                'keyboard_hide',
                'keyboard_return',
                'keyboard_tab',
                'keyboard_voice',
                'kitchen',
                'label',
                'label_outline',
                'landscape',
                'language',
                'laptop',
                'laptop_chromebook',
                'laptop_mac',
                'laptop_windows',
                'last_page',
                'launch',
                'layers',
                'layers_clear',
                'leak_add',
                'leak_remove',
                'lens',
                'library_add',
                'library_books',
                'library_music',
                'lightbulb_outline',
                'line_style',
                'line_weight',
                'linear_scale',
                'link',
                'linked_camera',
                'list',
                'live_help',
                'live_tv',
                'local_activity',
                'local_airport',
                'local_atm',
                'local_bar',
                'local_cafe',
                'local_car_wash',
                'local_convenience_store',
                'local_dining',
                'local_drink',
                'local_florist',
                'local_gas_station',
                'local_grocery_store',
                'local_hospital',
                'local_hotel',
                'local_laundry_service',
                'local_library',
                'local_mall',
                'local_movies',
                'local_offer',
                'local_parking',
                'local_pharmacy',
                'local_phone',
                'local_pizza',
                'local_play',
                'local_post_office',
                'local_printshop',
                'local_see',
                'local_shipping',
                'local_taxi',
                'location_city',
                'location_disabled',
                'location_off',
                'location_on',
                'location_searching',
                'lock',
                'lock_open',
                'lock_outline',
                'looks',
                'looks_one',
                'looks_two',
                'loop',
                'loupe',
                'loyalty',
                'low_priority',
                'mail',
                'mail_outline',
                'map',
                'markunread',
                'markunread_mailbox',
                'memory',
                'menu',
                'merge_type',
                'message',
                'messenger',
                'mic',
                'mic_none',
                'mic_off',
                'mms',
                'mode_comment',
                'mode_edit',
                'monetization_on',
                'money_off',
                'monochrome_photos',
                'mood',
                'mood_bad',
                'more',
                'more_horiz',
                'more_vert',
                'motorcycle',
                'mouse',
                'move_to_inbox',
                'movie',
                'movie_creation',
                'movie_filter',
                'multiline_chart',
                'music_note',
                'music_video',
                'my_location',
                'nature',
                'nature_people',
                'navigate_before',
                'navigate_next',
                'navigation',
                'near_me',
                'network_check',
                'network_locked',
                'network_cell',
                'network_wifi',
                'new_releases',
                'next_week',
                'nfc',
                'no_encryption',
                'no_sim',
                'not_interested',
                'note',
                'note_add',
                'notifications',
                'notifications_none',
                'notifications_off',
                'notifications_active',
                'notifications_paused',
                'offline_pin',
                'ondemand_video',
                'opacity',
                'open_in_browser',
                'open_in_new',
                'open_with',
                'pages',
                'pageview',
                'palette',
                'pan_tool',
                'panorama',
                'panorama_fish_eye',
                'panorama_horizontal',
                'panorama_vertical',
                'panorama_wide_angle',
                'party_mode',
                'pause',
                'pause_circle_filled',
                'pause_circle_outline',
                'payment',
                'people',
                'people_outline',
                'perm_camera_mic',
                'perm_contact_calendar',
                'perm_data_setting',
                'perm_device_information',
                'perm_identity',
                'perm_media',
                'perm_phone_msg',
                'perm_scan_wifi',
                'person',
                'person_add',
                'person_outline',
                'person_pin',
                'person_pin_circle',
                'personal_video',
                'pets',
                'phone',
                'phone_android',
                'phone_bluetooth_speaker',
                'phone_forwarded',
                'phone_in_talk',
                'phone_iphone',
                'phone_locked',
                'phone_missed',
                'phone_paused',
                'phonelink',
                'phonelink_erase',
                'phonelink_lock',
                'phonelink_off',
                'phonelink_ring',
                'phonelink_setup',
                'photo',
                'photo_album',
                'photo_camera',
                'photo_filter',
                'photo_library',
                'photo_size_select_actual',
                'photo_size_select_large',
                'photo_size_select_small',
                'picture_as_pdf',
                'picture_in_picture',
                'picture_in_picture_alt',
                'pie_chart',
                'pie_chart_outlined',
                'pin_drop',
                'place',
                'play_arrow',
                'play_circle_filled',
                'play_circle_outline',
                'play_for_work',
                'playlist_add',
                'playlist_add_check',
                'playlist_play',
                'plus_one',
                'poll',
                'polymer',
                'pool',
                'portable_wifi_off',
                'portrait',
                'power',
                'power_input',
                'power_settings_new',
                'pregnant_woman',
                'present_to_all',
                'publish',
                'print',
                'priority_high',
                'public',
                'query_builder',
                'question_answer',
                'queue',
                'queue_music',
                'queue_play_next',
                'radio',
                'radio_button_unchecked',
                'radio_button_checked',
                'rate_review',
                'receipt',
                'recent_actors',
                'record_voice_over',
                'redeem',
                'redo',
                'refresh',
                'remove',
                'remove_circle',
                'remove_circle_outline',
                'remove_from_queue',
                'remove_red_eye',
                'remove_shopping_cart',
                'reorder',
                'repeat',
                'repeat_one',
                'replay',
                'reply',
                'reply_all',
                'report',
                'report_problem',
                'restaurant',
                'restaurant_menu',
                'restore',
                'restore_page',
                'ring_volume',
                'room',
                'room_service',
                'rotate_90_degrees_ccw',
                'rotate_left',
                'rotate_right',
                'rounded_corner',
                'router',
                'rowing',
                'rss_feed',
                'rv_hookup',
                'satellite',
                'save',
                'scanner',
                'schedule',
                'school',
                'screen_lock_landscape',
                'screen_lock_portrait',
                'screen_lock_rotation',
                'screen_rotation',
                'screen_share',
                'sd_card',
                'sd_storage',
                'search',
                'security',
                'select_all',
                'send',
                'sentiment_dissatisfied',
                'sentiment_neutral',
                'sentiment_satisfied',
                'sentiment_very_dissatisfied',
                'sentiment_very_satisfied',
                'settings',
                'settings_applications',
                'settings_backup_restore',
                'settings_bluetooth',
                'settings_brightness',
                'settings_cell',
                'settings_ethernet',
                'settings_input_antenna',
                'settings_input_component',
                'settings_input_composite',
                'settings_input_hdmi',
                'settings_input_svideo',
                'settings_overscan',
                'settings_phone',
                'settings_power',
                'settings_remote',
                'settings_system_daydream',
                'settings_voice',
                'share',
                'shop',
                'shop_two',
                'shopping_basket',
                'shopping_cart',
                'short_text',
                'show_chart',
                'shuffle',
                'signal_cellular_4_bar',
                'signal_cellular_connected_no_internet_4_bar',
                'signal_cellular_no_sim',
                'signal_cellular_null',
                'signal_cellular_off',
                'signal_wifi_4_bar',
                'signal_wifi_4_bar_lock',
                'signal_wifi_off',
                'sim_card',
                'sim_card_alert',
                'skip_next',
                'skip_previous',
                'slideshow',
                'slow_motion_video',
                'smartphone',
                'smoke_free',
                'smoking_rooms',
                'sms',
                'sms_failed',
                'snooze',
                'sort',
                'sort_by_alpha',
                'spa',
                'space_bar',
                'speaker',
                'speaker_group',
                'speaker_notes',
                'speaker_notes_off',
                'speaker_phone',
                'spellcheck',
                'star',
                'star_half',
                'star_border',
                'stars',
                'stay_current_landscape',
                'stay_current_portrait',
                'stay_primary_landscape',
                'stay_primary_portrait',
                'stop',
                'stop_screen_share',
                'storage',
                'store',
                'store_mall_directory',
                'streetview',
                'straighten',
                'strikethrough_s',
                'style',
                'subdirectory_arrow_left',
                'subdirectory_arrow_right',
                'subject',
                'subscriptions',
                'subtitles',
                'subway',
                'supervisor_account',
                'surround_sound',
                'swap_calls',
                'swap_horiz',
                'swap_vert',
                'swap_vertical_circle',
                'switch_camera',
                'switch_video',
                'sync',
                'sync_disabled',
                'sync_problem',
                'system_update',
                'system_update_alt',
                'tab',
                'tab_unselected',
                'tablet',
                'tablet_android',
                'tablet_mac',
                'tag_faces',
                'tap_and_play',
                'terrain',
                'text_fields',
                'text_format',
                'textsms',
                'texture',
                'theaters',
                'thumb_down',
                'thumb_up',
                'thumbs_up_down',
                'timelapse',
                'time_to_leave',
                'timer',
                'timer_off',
                'title',
                'toc',
                'today',
                'toll',
                'tonality',
                'touch_app',
                'toys',
                'track_changes',
                'traffic',
                'train',
                'tram',
                'transfer_within_a_station',
                'transform',
                'translate',
                'trending_down',
                'trending_flat',
                'trending_up',
                'tune',
                'turned_in',
                'turned_in_not',
                'tv',
                'unarchive',
                'undo',
                'unfold_less',
                'unfold_more',
                'update',
                'usb',
                'verified_user',
                'vertical_align_bottom',
                'vertical_align_center',
                'vertical_align_top',
                'vibration',
                'video_call',
                'video_label',
                'video_library',
                'videocam',
                'videocam_off',
                'videogame_asset',
                'view_agenda',
                'view_array',
                'view_carousel',
                'view_column',
                'view_comfy',
                'view_compact',
                'view_day',
                'view_headline',
                'view_list',
                'view_module',
                'view_quilt',
                'view_stream',
                'view_week',
                'vignette',
                'visibility',
                'visibility_off',
                'voice_chat',
                'voicemail',
                'volume_down',
                'volume_mute',
                'volume_off',
                'volume_up',
                'vpn_key',
                'vpn_lock',
                'wallpaper',
                'warning',
                'watch',
                'wb_auto',
                'wb_cloudy',
                'wb_incandescent',
                'wb_iridescent',
                'wb_sunny',
                'wc',
                'web',
                'web_asset',
                'weekend',
                'widgets',
                'wifi',
                'wifi_lock',
                'wifi_tethering',
                'whatshot',
                'work',
                'wrap_text',
                'youtube_searched_for',
                'zoom_in',
                'zoom_out',
                'zoom_out_map'];
    }
};